### PR TITLE
Support for sending image attachments with messages

### PR DESCRIPTION
**Pull request by chevell**
This adds support for [pushing images with Pushover 3.0](https://updates.pushover.net/post/170043375237/pushing-images-with-pushover-30)

Clients simply include a file-like object via the `attachment` keyword when sending a message. A trivial example looks like this:

```python
messenger = pushover.Client(PUSHOVER_USER_KEY, api_token=PUSHOVER_API_TOKEN)

with open('/path/to/my/image.png', 'rb') as image:
    messenger.send_message('Test message with image', attachment=image)
```

### CODE REVIEW

**Comment by diogopms** [comment]
@chevell, thanks for creating this PR 👍

What do you think about supporting public URL's too?

ex:
```
messenger.send_message('Test message with image', url='https://www.google.pt/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png')
```

**Comment by Thibauth** [comment]
Hi @chevell thanks so much for the PR, this is a great feature to add! I will try to have a more detailed look in the next couple of days and merge this.

@diogopms This is a good point, but it also feels a bit that this is something which should be done outside of this library: given that downloading a URL into a file can be done in one file of python, it feels to me that this should be done first, and then you can use the library as @chevell designed it. I don't have strong opinions about this though, and could easily be convinced otherwise if you think there is a good use case for the API to look like what you are suggesting.

@chevell @diogopms any thoughts?

**Comment by chevell** [comment]
@diogopms @Thibauth it’s a cool idea but I’d recommend against it. As a user I would expect this library to reflect the API’s own functionality, and in seeing this sort of feature I would assume the API supported passing image URL’s natively. Discovering `send_message` was having to download an image on each call would break my expectations around speed and bandwidth usage.

**Comment by chevell** [comment]
@Thibauth any other feedback on this one?

**Comment by Thibauth** [comment]
@chevell sorry for the delay. I just had a more detailed look at the PR and it looks perfect to me. Merging now.

About supporting passing image URL's I agree with @chevell 's opinion: it seems better to restrict the features to what is supported by the pushover API. Downloading a URL into a file would be better done outside of this library (and as mentioned above is only a one-liner anyway).

**Pull request merged**
